import pandas as pd
import streamlit as st
import plotly.express as px


st.set_page_config(
    page_title="Life Insurance Reserve Engine",
    layout="wide"
)


@st.cache_data
def load_data():
    reserve_df = pd.read_csv("output/reserve_report.csv")
    reinsurance_df = pd.read_csv("output/reinsurance_report.csv")
    premium_df = pd.read_csv("output/premium_report.csv")

    df = reserve_df.merge(
        reinsurance_df,
        on=["policy_id", "insured_id", "product_type", "face_amount"],
        how="left"
    )

    df = df.merge(
        premium_df,
        on=["policy_id", "insured_id", "product_type", "annual_premium", "ceded_premium"],
        how="left"
    )

    return df


def format_currency(value):
    return f"${value:,.0f}"


df = load_data()

st.title("Life Insurance Reserve & Reinsurance Valuation Platform")

st.markdown(
    """
    This dashboard presents portfolio-level reserve, mortality, premium, 
    and reinsurance analytics generated by a Python-based actuarial valuation engine.
    """
)

# Sidebar filters
st.sidebar.header("Filters")

product_filter = st.sidebar.multiselect(
    "Product Type",
    options=sorted(df["product_type"].unique()),
    default=sorted(df["product_type"].unique())
)

status_filter = st.sidebar.multiselect(
    "Policy Status",
    options=sorted(df["policy_status"].unique()),
    default=sorted(df["policy_status"].unique())
)

filtered_df = df[
    (df["product_type"].isin(product_filter)) &
    (df["policy_status"].isin(status_filter))
]

# Tabs
tab1, tab2, tab3, tab4, tab5, tab6, tab7 = st.tabs([
    "Executive Summary",
    "Reserve Analytics",
    "Mortality Analytics",
    "Reinsurance Analytics",
    "Policy Drilldown",
    "Policy Valuation & Scenario Testing",
    "Mortality Rate Lookup"
])

with tab1:
    st.header("Executive Summary")

    total_policies = filtered_df["policy_id"].nunique()
    total_reserve = filtered_df["reserve"].sum()
    total_face_amount = filtered_df["face_amount"].sum()
    total_ceded_premium = filtered_df["ceded_premium"].sum()
    average_age = filtered_df["current_age"].mean()
    active_rate = (
        filtered_df[filtered_df["policy_status"] == "Active"]["policy_id"].nunique()
        / total_policies
        if total_policies > 0 else 0
    )

    col1, col2, col3 = st.columns(3)
    col1.metric("Total Policies", f"{total_policies:,}")
    col2.metric("Total Reserve", format_currency(total_reserve))
    col3.metric("Total Face Amount", format_currency(total_face_amount))

    col4, col5, col6 = st.columns(3)
    col4.metric("Total Ceded Premium", format_currency(total_ceded_premium))
    col5.metric("Average Current Age", f"{average_age:.1f}")
    col6.metric("Active Policy Rate", f"{active_rate:.1%}")

    st.subheader("Portfolio by Product Type")

    product_summary = filtered_df.groupby("product_type", as_index=False).agg(
        policy_count=("policy_id", "nunique"),
        total_reserve=("reserve", "sum"),
        total_face_amount=("face_amount", "sum"),
        total_ceded_premium=("ceded_premium", "sum")
    )

    st.dataframe(product_summary, use_container_width=True)

with tab2:
    st.header("Reserve Analytics")

    reserve_by_product = filtered_df.groupby("product_type", as_index=False)["reserve"].sum()

    fig1 = px.bar(
        reserve_by_product,
        x="product_type",
        y="reserve",
        title="Total Reserve by Product Type"
    )
    st.plotly_chart(fig1, use_container_width=True)

    filtered_df["age_band"] = pd.cut(
        filtered_df["current_age"],
        bins=[0, 30, 40, 50, 60, 70, 80, 120],
        labels=["<30", "30-39", "40-49", "50-59", "60-69", "70-79", "80+"]
    )

    reserve_by_age = filtered_df.groupby("age_band", as_index=False, observed=True)["reserve"].sum()

    fig2 = px.bar(
        reserve_by_age,
        x="age_band",
        y="reserve",
        title="Total Reserve by Age Band"
    )
    st.plotly_chart(fig2, use_container_width=True)

    fig3 = px.histogram(
        filtered_df,
        x="reserve",
        nbins=50,
        title="Reserve Distribution"
    )
    st.plotly_chart(fig3, use_container_width=True)

with tab3:
    st.header("Mortality Analytics")

    mortality_by_age = filtered_df.groupby("current_age", as_index=False).agg(
        average_qx=("qx", "mean"),
        expected_claim=("expected_claim", "sum")
    )

    fig4 = px.line(
        mortality_by_age,
        x="current_age",
        y="average_qx",
        title="Average Mortality Rate by Age"
    )
    st.plotly_chart(fig4, use_container_width=True)

    mortality_by_gender = filtered_df.groupby(["current_age", "gender"], as_index=False)["qx"].mean()

    fig5 = px.line(
        mortality_by_gender,
        x="current_age",
        y="qx",
        color="gender",
        title="Mortality Rate by Age and Gender"
    )
    st.plotly_chart(fig5, use_container_width=True)

    fig6 = px.bar(
        mortality_by_age,
        x="current_age",
        y="expected_claim",
        title="Expected Claims by Age"
    )
    st.plotly_chart(fig6, use_container_width=True)

with tab4:
    st.header("Reinsurance Analytics")

    reinsurance_by_product = filtered_df.groupby("product_type", as_index=False).agg(
        total_reinsured_amount=("reinsured_amount", "sum"),
        total_ceded_premium=("ceded_premium", "sum"),
        total_face_amount=("face_amount", "sum")
    )

    reinsurance_by_product["ceded_ratio"] = (
        reinsurance_by_product["total_reinsured_amount"]
        / reinsurance_by_product["total_face_amount"]
    )

    fig7 = px.bar(
        reinsurance_by_product,
        x="product_type",
        y="total_reinsured_amount",
        title="Reinsured Amount by Product Type"
    )
    st.plotly_chart(fig7, use_container_width=True)

    fig8 = px.bar(
        reinsurance_by_product,
        x="product_type",
        y="total_ceded_premium",
        title="Ceded Premium by Product Type"
    )
    st.plotly_chart(fig8, use_container_width=True)

    st.subheader("Retention Limit Analysis")

    retention_summary = filtered_df.groupby("retention_limit", as_index=False).agg(
        policy_count=("policy_id", "nunique"),
        total_face_amount=("face_amount", "sum"),
        total_reinsured_amount=("reinsured_amount", "sum"),
        total_ceded_premium=("ceded_premium", "sum")
    )

    st.dataframe(retention_summary, use_container_width=True)

with tab5:
    st.header("Policy Drilldown")

    selected_policy = st.selectbox(
        "Select Policy ID",
        options=sorted(filtered_df["policy_id"].unique())
    )

    policy_detail = filtered_df[filtered_df["policy_id"] == selected_policy].iloc[0]

    col1, col2 = st.columns(2)

    with col1:
        st.subheader("Policy Information")
        st.write(f"**Policy ID:** {policy_detail['policy_id']}")
        st.write(f"**Insured ID:** {policy_detail['insured_id']}")
        st.write(f"**Product Type:** {policy_detail['product_type']}")
        st.write(f"**Policy Status:** {policy_detail['policy_status']}")
        st.write(f"**Gender:** {policy_detail['gender']}")
        st.write(f"**Current Age:** {policy_detail['current_age']}")

    with col2:
        st.subheader("Valuation Results")
        st.write(f"**Face Amount:** {format_currency(policy_detail['face_amount'])}")
        st.write(f"**Annual Premium:** {format_currency(policy_detail['annual_premium'])}")
        st.write(f"**Mortality Rate qx:** {policy_detail['qx']:.6f}")
        st.write(f"**Expected Claim:** {format_currency(policy_detail['expected_claim'])}")
        st.write(f"**Reserve:** {format_currency(policy_detail['reserve'])}")
        st.write(f"**Retention Limit:** {format_currency(policy_detail['retention_limit'])}")
        st.write(f"**Reinsured Amount:** {format_currency(policy_detail['reinsured_amount'])}")
        st.write(f"**Ceded Premium:** {format_currency(policy_detail['ceded_premium'])}")


with tab6:
    st.header("Policy Valuation & Scenario Testing")

    st.markdown(
        """
        Enter policy assumptions to estimate expected claim, reserve, retention limit,
        reinsured amount, and ceded premium. Then use the scenario sliders below
        to test assumption sensitivity.
        """
    )

    st.subheader("Base Policy Inputs")

    col1, col2 = st.columns(2)

    with col1:
        input_sex = st.selectbox(
            "Sex",
            options=["Male", "Female"],
            key="valuation_sex"
        )

        input_current_age = st.number_input(
            "Attained Age",
            min_value=0,
            max_value=119,
            value=45,
            key="valuation_attained_age"
        )

        input_issue_year = st.number_input(
            "Issue Year",
            min_value=1900,
            max_value=2026,
            value=2020,
            key="valuation_issue_year"
        )

        input_product_type = st.selectbox(
            "Product Type",
            options=["Term Life", "Whole Life", "Universal Life"],
            key="valuation_product_type"
        )

    with col2:
        input_face_amount = st.number_input(
            "Death Benefit / Face Amount",
            min_value=0.0,
            value=1_000_000.0,
            step=50_000.0,
            key="valuation_face_amount"
        )

        input_annual_premium = st.number_input(
            "Annual Premium",
            min_value=0.0,
            value=5_000.0,
            step=500.0,
            key="valuation_annual_premium"
        )

        input_policy_term = st.number_input(
            "Policy Term",
            min_value=1,
            max_value=100,
            value=20,
            key="valuation_policy_term"
        )

        input_policy_duration = st.number_input(
            "Policy Duration",
            min_value=0,
            max_value=100,
            value=5,
            key="valuation_policy_duration"
        )

    remaining_term = int(input_policy_term - input_policy_duration)

    if remaining_term <= 0:
        st.error("Policy duration must be less than policy term.")
    else:
        mortality_table = pd.read_csv("data/mortality_table.csv")
        mortality_row = mortality_table[mortality_table["age"] == input_current_age]

        if mortality_row.empty:
            st.error("No mortality assumption found for the selected age.")
        else:
            if input_sex == "Male":
                base_mortality_rate = float(mortality_row.iloc[0]["male_qx"])
            else:
                base_mortality_rate = float(mortality_row.iloc[0]["female_qx"])

            base_discount_rate = 0.03
            reinsurance_rate = 0.0015

            if input_issue_year < 2018:
                base_retention_limit = 3_000_000
            else:
                base_retention_limit = 2_000_000

            base_expected_claim = input_face_amount * base_mortality_rate

            base_pv_future_claims = sum(
                base_expected_claim / ((1 + base_discount_rate) ** t)
                for t in range(1, remaining_term + 1)
            )

            base_pv_future_premiums = sum(
                input_annual_premium / ((1 + base_discount_rate) ** t)
                for t in range(1, remaining_term + 1)
            )

            base_reserve = max(base_pv_future_claims - base_pv_future_premiums, 0)
            base_reinsured_amount = max(0, input_face_amount - base_retention_limit)
            base_ceded_premium = base_reinsured_amount * reinsurance_rate

            st.subheader("Base Valuation Results")

            col1, col2, col3 = st.columns(3)
            col1.metric("Expected Claim", format_currency(base_expected_claim))
            col2.metric("Reserve", format_currency(base_reserve))
            col3.metric("Annual Mortality Rate", f"{base_mortality_rate:.6f}")

            col4, col5, col6 = st.columns(3)
            col4.metric("Retention Limit", format_currency(base_retention_limit))
            col5.metric("Reinsured Amount", format_currency(base_reinsured_amount))
            col6.metric("Ceded Premium", format_currency(base_ceded_premium))

            st.divider()

            st.subheader("Scenario Testing")

            col7, col8, col9 = st.columns(3)

            with col7:
                mortality_shock = st.slider(
                    "Mortality Shock",
                    min_value=-50,
                    max_value=100,
                    value=0,
                    step=5,
                    format="%d%%",
                    key="scenario_mortality_shock"
                ) / 100

            with col8:
                scenario_discount_rate = st.slider(
                    "Discount Rate",
                    min_value=0.00,
                    max_value=0.10,
                    value=0.03,
                    step=0.005,
                    format="%.3f",
                    key="scenario_discount_rate"
                )

            with col9:
                scenario_retention_limit = st.slider(
                    "Retention Limit",
                    min_value=1_000_000,
                    max_value=5_000_000,
                    value=int(base_retention_limit),
                    step=250_000,
                    key="scenario_retention_limit"
                )

            scenario_mortality_rate = base_mortality_rate * (1 + mortality_shock)
            scenario_expected_claim = input_face_amount * scenario_mortality_rate

            scenario_pv_future_claims = sum(
                scenario_expected_claim / ((1 + scenario_discount_rate) ** t)
                for t in range(1, remaining_term + 1)
            )

            scenario_pv_future_premiums = sum(
                input_annual_premium / ((1 + scenario_discount_rate) ** t)
                for t in range(1, remaining_term + 1)
            )

            scenario_reserve = max(
                scenario_pv_future_claims - scenario_pv_future_premiums,
                0
            )

            scenario_reinsured_amount = max(
                0,
                input_face_amount - scenario_retention_limit
            )

            scenario_ceded_premium = scenario_reinsured_amount * reinsurance_rate

            reserve_change = scenario_reserve - base_reserve
            ceded_premium_change = scenario_ceded_premium - base_ceded_premium
            expected_claim_change = scenario_expected_claim - base_expected_claim

            st.subheader("Scenario Impact")

            col10, col11, col12 = st.columns(3)

            col10.metric(
                "Scenario Expected Claim",
                format_currency(scenario_expected_claim),
                delta=format_currency(expected_claim_change)
            )

            col11.metric(
                "Scenario Reserve",
                format_currency(scenario_reserve),
                delta=format_currency(reserve_change)
            )

            col12.metric(
                "Scenario Ceded Premium",
                format_currency(scenario_ceded_premium),
                delta=format_currency(ceded_premium_change)
            )

            col13, col14, col15 = st.columns(3)

            col13.metric(
                "Scenario Annual Mortality Rate",
                f"{scenario_mortality_rate:.6f}"
            )

            col14.metric(
                "Scenario Retention Limit",
                format_currency(scenario_retention_limit)
            )

            col15.metric(
                "Scenario Reinsured Amount",
                format_currency(scenario_reinsured_amount)
            )


with tab7:
    st.header("Mortality Rate Lookup")

    st.markdown(
        """
        Search the mortality assumption table by attained age and sex.
        The displayed rate represents the one-year probability of death.
        """
    )

    mortality_table = pd.read_csv("data/mortality_table.csv")

    col1, col2 = st.columns(2)

    with col1:
        lookup_age = st.number_input(
            "Attained Age",
            min_value=0,
            max_value=119,
            value=45,
            key="mortality_lookup_attained_age"
        )

    with col2:
        lookup_sex = st.selectbox(
            "Sex",
            options=["Male", "Female"],
            key="mortality_lookup_sex"
        )

    mortality_row = mortality_table[mortality_table["age"] == lookup_age]

    if mortality_row.empty:
        st.error("No mortality assumption found for the selected age.")
    else:
        if lookup_sex == "Male":
            annual_mortality_rate = float(mortality_row.iloc[0]["male_qx"])
        else:
            annual_mortality_rate = float(mortality_row.iloc[0]["female_qx"])

        st.subheader("Mortality Assumption Result")

        col1, col2, col3 = st.columns(3)

        col1.metric("Attained Age", lookup_age)
        col2.metric("Sex", lookup_sex)
        col3.metric("Annual Mortality Rate", f"{annual_mortality_rate:.6f}")


        st.subheader("Male vs Female Comparison at Selected Age")

        comparison_df = pd.DataFrame([
            {
                "Sex": "Male",
                "Annual Mortality Rate": float(mortality_row.iloc[0]["male_qx"]),
                "One-Year Death Probability": f"{float(mortality_row.iloc[0]['male_qx']):.4%}"
            },
            {
                "Sex": "Female",
                "Annual Mortality Rate": float(mortality_row.iloc[0]["female_qx"]),
                "One-Year Death Probability": f"{float(mortality_row.iloc[0]['female_qx']):.4%}"
            }
        ])

        st.dataframe(comparison_df, use_container_width=True)